version: '3.3'

services:

  db:
    image: mysql:latest
    restart: always
    container_name: db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3306"
    ports:
      - '33061:3306'
    volumes:
      - ./backend/scripts/db.sql:/docker-entrypoint-initdb.d/init.sql



